### ISSUE TITLE
filters for \input

### ISSUE THREAD

**Issue by b-stone** [adelphimathcs/Active-Calculus#5]
I have created a ruby script to import all files that are from `\input`. Next is to create a make file.

**Comment by MichaelVessia** [comment]
There is already a Makefile at https://github.com/adelphimathcs/Active-Calculus/blob/gh-pages/Makefile, would this one be for something else?

**Comment by b-stone** [comment]
I meant edit the current make file. That one is for making a different type of book. The concept is the same though. I have added `tex_input` to that file. In the end this makefile will be the one that creates the epub, tex, and pdf of the web book .

**Comment by b-stone** [comment]
Concerning the tex files that are imported via `\input`, I have that working. I now need to work on making sure what is imported is actually the content I want. Basically I need to include some sort of while loop in the ruby script `tools/use_tex_input.rb` that would stop the script when a certain line is read. I just need to figure out what line.

**Comment by b-stone** [comment]
The filter concept is implemented. I just need to apply it to many different instances.
